### ISSUE TITLE
Need help, I have an error I tried to fix it but I was not able.

### ISSUE THREAD

**Issue by yelkamel** [RGLie/word_cloud#2]
Hello,

I'm looking to use your packages for my app Beedone.

But it's not working on my emulator iPhone 14
with
``` 
 return Scaffold(
      appBar: AppBar(),
      body: WordCloudView2(
        data: WordCloudData(data: [
          {'word': 'Apple', 'value': 100.0},
          {'word': 'Samsung', 'value': 60.0},
        ]),
        // mapcolor: const Color.fromARGB(255, 174, 183, 235),
        mapwidth: 300.1,
        mapheight: 300.1,
        // shape: WordCloudCircle(radius: 250.0),
      ),
    );
```

I have that:

![word_cloud_error](https://github.com/RGLie/word_cloud/assets/10924422/03e5303d-b746-40de-be4a-6659d482d3a4)

Can you help me ?
Thanks

**Comment by frankjmclarke** [comment]
Same problem in Android. Works in Chrome.

**Comment by devadarshan2-3** [comment]
same issue....

**Comment by haim1121** [comment]
Follow where the error occurred to find the `word_cloud_setting.dart` file. In the function `checkMapOptimized`, `h` can double type, but in the `map[i][y + h - 1]` code, `h` is contained inside the index. I changed the code `map[i][y + h - 1]` to `map[i][y + h.toInt() - 1]` and solved it. But I'm not a developer, so I'm not sure if this is the perfect answer. Most of them run well after fixing this. (You can easily find the internal code by finding checkMapOptimized by scope.)

**Comment by timozuther** [comment]
Is anyone actively working on this to integrate the changes?
